# Generated by Django 4.0.4 on 2022-05-08 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0024_delete_message'),
        ('message', '0002_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='shared_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubica.post'),
        ),
    ]
