# Generated by Django 4.0.4 on 2022-05-05 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0003_alter_comment_person_alter_post_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='person',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cubica.person'),
        ),
        migrations.AlterField(
            model_name='post',
            name='person',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cubica.person'),
        ),
        migrations.CreateModel(
            name='SubCube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubica.person')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubica.post')),
            ],
        ),
    ]
