# Generated by Django 4.0.4 on 2022-05-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0005_remove_subcube_people_subcube_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cubica.person'),
        ),
        migrations.RemoveField(
            model_name='subcube',
            name='posts',
        ),
        migrations.AddField(
            model_name='subcube',
            name='posts',
            field=models.ManyToManyField(to='cubica.post'),
        ),
    ]
