# Generated by Django 4.0.4 on 2022-05-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0006_alter_comment_person_remove_subcube_posts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_text', models.CharField(max_length=200)),
                ('achievement_points', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='achievements',
            field=models.ManyToManyField(to='cubica.achievement'),
        ),
    ]
