# Generated by Django 4.0.4 on 2022-05-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0007_achievement_person_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pic',
            field=models.ImageField(default=None, upload_to='static/cubica/images'),
        ),
    ]
