# Generated by Django 4.0.4 on 2022-05-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0008_person_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pic',
        ),
    ]
