# Generated by Django 4.0.4 on 2022-05-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0009_remove_person_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pic',
            field=models.ImageField(default=None, upload_to='static/cubica/images'),
        ),
    ]
