# Generated by Django 4.0.4 on 2022-05-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0010_person_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pic',
        ),
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(default=None, upload_to='static/cubica/profile_images'),
        ),
    ]
