# Generated by Django 4.0.4 on 2022-05-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0011_remove_person_pic_post_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(default=None, upload_to='static/cubica/images'),
        ),
    ]
