# Generated by Django 4.0.4 on 2022-05-07 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0012_alter_post_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcube',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='subcube',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cubica.subcube'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
