# Generated by Django 4.0.4 on 2022-05-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0013_remove_subcube_posts_post_subcube_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subcube',
        ),
        migrations.AddField(
            model_name='subcube',
            name='posts',
            field=models.ManyToManyField(to='cubica.post'),
        ),
    ]
