# Generated by Django 4.0.4 on 2022-05-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0014_remove_post_subcube_subcube_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcube',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='subcube',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cubica.subcube'),
        ),
    ]
