# Generated by Django 4.0.4 on 2022-05-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0015_remove_subcube_posts_post_subcube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cubica.person'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcube',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cubica.subcube'),
        ),
    ]
