# Generated by Django 4.0.4 on 2022-05-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0017_alter_post_post_text_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_name',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
