# Generated by Django 4.0.4 on 2022-05-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0018_post_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
