# Generated by Django 4.0.4 on 2022-05-08 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0020_alter_post_post_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('sent_date', models.DateTimeField(auto_now_add=True, verbose_name='date sent')),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='cubica.person')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='cubica.person')),
                ('shared_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cubica.post')),
            ],
        ),
    ]
