# Generated by Django 4.0.4 on 2022-05-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0021_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_date',
            field=models.DateTimeField(verbose_name='date sent'),
        ),
    ]
