# Generated by Django 4.0.4 on 2022-05-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0023_alter_message_sent_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
