# Generated by Django 4.0.4 on 2022-05-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0024_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(default='static/cubica/profile_images/default_profile.jpg', upload_to='static/cubica/profile_images'),
        ),
        migrations.AddField(
            model_name='subcube',
            name='subcube_pic',
            field=models.ImageField(default='static/cubica/other/group.png', upload_to='static/cubica/other'),
        ),
    ]
