# Generated by Django 4.0.4 on 2022-05-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0025_person_profile_pic_subcube_subcube_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcube',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
