# Generated by Django 4.0.4 on 2022-05-09 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0027_person_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='achievements',
        ),
        migrations.AddField(
            model_name='person',
            name='achievements',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cubica.achievement'),
        ),
    ]
