# Generated by Django 4.0.4 on 2022-05-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0028_remove_person_achievements_person_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='achievements',
        ),
        migrations.AddField(
            model_name='person',
            name='achievements',
            field=models.ManyToManyField(to='cubica.achievement'),
        ),
    ]
