# Generated by Django 4.0.4 on 2022-05-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubica', '0029_remove_person_achievements_person_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
